import { EventBus } from '../core/EventBus'; import type { TacticalMap } from '../data/tactical/TacticalMap'; import type { GridPoint } from '../world/GridCoordinates'; import { gridKey } from '../world/GridCoordinates'; import { movementRange } from '../world/MovementRange'; import { Pathfinder } from '../world/Pathfinder'; import type { BattleEvents } from './BattleEvents'; import { createBattleSnapshot, validateBattleSnapshot, type BattleSnapshot } from './BattleSave'; import { CombatResolver, type ActionResult } from './CombatResolver'; import type { AttackPreview } from './CombatFormula'; import type { AiProfile, BattleDefinition, CombatData, Facing, UnitBattleState, UnitId, WeaponProfile } from './CombatTypes'; import { EnemyAI, type AiDecision } from './EnemyAI'; import { facingFromMovement } from './Facing'; import { Initiative } from './Initiative'; import { ObjectiveTracker } from './Objectives'; import { Occupancy } from './Occupancy'; import { SeededRandom } from './SeededRandom'; import { StatusSystem } from './StatusSystem'; import { TurnStateMachine } from './TurnStateMachine'; import { changeFacing, cloneUnit, createUnit, moveUnit } from './UnitModel';
export class BattleController {
  readonly events = new EventBus<BattleEvents>(); readonly units: UnitBattleState[]; readonly occupancy = new Occupancy(); readonly statuses: StatusSystem; readonly initiative: Initiative; readonly turns = new TurnStateMachine(); readonly objectives: ObjectiveTracker; readonly random: SeededRandom; readonly pathfinder = new Pathfinder(); readonly resolver: CombatResolver; readonly ai = new EnemyAI(); readonly log: string[] = []; activeUnit: UnitBattleState | undefined; lastAiDecision: AiDecision | undefined;
  private readonly weapons: ReadonlyMap<string, WeaponProfile>; private readonly aiProfiles: ReadonlyMap<string, AiProfile>;
  constructor(readonly map: TacticalMap, readonly data: CombatData, readonly definition: BattleDefinition) { const templates = new Map(data.templates.map((template) => [template.id, template])); this.units = definition.units.map((placement) => { const template = templates.get(placement.templateId); if (!template) throw new Error(`Missing template ${placement.templateId}.`); if (!map.inBounds(placement.position.x, placement.position.y) || !map.require(placement.position.x, placement.position.y).walkable) throw new Error(`Invalid spawn for ${placement.id}.`); return createUnit(template, placement); }); this.occupancy.rebuild(this.units); this.statuses = new StatusSystem(data.statuses); this.initiative = new Initiative(this.units, this.statuses); this.objectives = new ObjectiveTracker(definition.objectives); this.random = new SeededRandom(definition.seed); this.weapons = new Map(data.weapons.map((weapon) => [weapon.id, weapon])); this.aiProfiles = new Map(data.aiProfiles.map((profile) => [profile.id, profile])); this.resolver = new CombatResolver(map, this.weapons, this.occupancy, this.statuses, this.random); }
  start(): UnitBattleState { this.turns.transition('initiativeAdvancing'); this.events.emit('battleStarted', { battleId: this.definition.id }); return this.nextTurn(); }
  nextTurn(): UnitBattleState { const result = this.objectives.evaluate(this.units); if (result !== 'ongoing') { this.turns.transition(result === 'won' ? 'battleWon' : 'battleLost'); this.events.emit(result === 'won' ? 'battleWon' : 'battleLost', {}); throw new BattleComplete(result); } this.activeUnit = this.initiative.advance(); this.events.emit('initiativeAdvanced', { activeUnitId: this.activeUnit.id }); this.turns.transition('turnStarting'); this.events.emit('turnStarted', { unitId: this.activeUnit.id }); this.turns.transition(this.activeUnit.controllable ? 'awaitingCommand' : 'enemyThinking'); return this.activeUnit; }
  reachable(): ReturnType<typeof movementRange> { const actor = this.requireActive(); return movementRange(this.map, actor.position, actor.move, { occupied: this.occupancy.blockedKeys(actor.id), maxElevationDelta: actor.jump }); }
  moveActive(destination: GridPoint): readonly GridPoint[] { const actor = this.requireActive(); if (this.turns.hasMoved) throw new Error('Move already used.'); const phase = this.turns.phase; this.turns.transition(phase === 'enemyThinking' ? 'executingMovement' : 'previewingMovement'); if (this.turns.phase === 'previewingMovement') this.turns.transition('executingMovement'); const reachable = this.reachable(); if (!reachable.has(gridKey(destination))) throw new Error('Destination is not reachable.'); const path = this.pathfinder.find(this.map, actor.position, destination, { occupied: this.occupancy.blockedKeys(actor.id), maxElevationDelta: actor.jump }); if (!path.found) throw new Error('Committed path is invalid.'); const from = actor.position; this.occupancy.reserve(actor.id, destination); changeFacing(actor, facingFromMovement(from, destination)); moveUnit(actor, destination.x, destination.y); this.occupancy.commitMove(actor.id, from, destination); this.turns.consumeMove(); this.events.emit('movementCompleted', { unitId: actor.id }); this.turns.transition(actor.controllable ? 'awaitingCommand' : 'enemyThinking'); return path.path; }
  previewAttack(targetId: UnitId): AttackPreview { const actor = this.requireActive(); const target = this.requireUnit(targetId); return this.resolver.preview(actor, target); }
  attack(targetId: UnitId): ActionResult { const actor = this.requireActive(); if (this.turns.hasActed) throw new Error('Action already used.'); if (actor.controllable) { this.turns.transition('choosingAction'); this.turns.transition('choosingTarget'); this.turns.transition('previewingAction'); this.turns.transition('executingAction'); } else this.turns.transition('executingAction'); const target = this.requireUnit(targetId); const result = this.resolver.resolve(actor, target); this.turns.consumeAction(); this.events.emit('attackResolved', result); for (const event of result.events) this.addLog(event); this.turns.transition('resolvingEffects'); const outcome = this.objectives.evaluate(this.units); if (outcome === 'won' || outcome === 'lost') this.turns.transition(outcome === 'won' ? 'battleWon' : 'battleLost'); else this.turns.transition(actor.controllable ? 'awaitingCommand' : 'enemyThinking'); return result; }
  setFacing(facing: Facing): void { changeFacing(this.requireActive(), facing); }
  endTurn(): UnitBattleState | undefined { const actor = this.requireActive(); this.turns.transition('turnEnding'); for (const event of this.statuses.processTurnEnd(actor)) this.addLog(event); if (!actor.alive) this.occupancy.remove(actor.id); this.initiative.completeTurn(actor.id); this.events.emit('turnEnded', { unitId: actor.id }); this.activeUnit = undefined; const outcome = this.objectives.evaluate(this.units); if (outcome !== 'ongoing') { this.turns.transition(outcome === 'won' ? 'battleWon' : 'battleLost'); return undefined; } this.turns.transition('initiativeAdvancing'); return this.nextTurn(); }
  runEnemyTurn(): { readonly actorId: UnitId; readonly path: readonly GridPoint[]; readonly action?: ActionResult } { const actor = this.requireActive(); if (actor.controllable || this.turns.phase !== 'enemyThinking') throw new Error('No enemy turn is ready.'); const actorId = actor.id; const profile = this.aiProfiles.get(actor.aiProfile); if (!profile) throw new Error(`Missing AI profile ${actor.aiProfile}.`); const decision = this.ai.decide(actor, this.units, this.map, profile, this.occupancy, this.pathfinder, this.resolver); this.lastAiDecision = decision; let path: readonly GridPoint[] = []; let action: ActionResult | undefined; if ((decision.destination.x !== actor.position.x || decision.destination.y !== actor.position.y) && !this.turns.hasMoved) path = this.moveActive(decision.destination); if (decision.targetId && !this.turns.hasActed) action = this.attack(decision.targetId); if (!this.terminal()) this.endTurn(); return { actorId, path, action }; }
  snapshot(): BattleSnapshot { return createBattleSnapshot(this.definition.mapId, this.units, this.activeUnit?.id, this.initiative.serialize(), this.turns.phase, this.turns.hasMoved, this.turns.hasActed, this.objectives.states, this.random.state, this.log); }
  restore(snapshot: unknown): void { if (!validateBattleSnapshot(snapshot) || snapshot.mapId !== this.definition.mapId) throw new Error('Invalid battle snapshot.'); if (snapshot.units.length !== this.units.length) throw new Error('Battle snapshot unit count mismatch.'); for (const saved of snapshot.units) { const index = this.units.findIndex((unit) => unit.id === saved.id); if (index < 0) throw new Error(`Unknown saved unit ${saved.id}.`); this.units[index] = cloneUnit(saved); } this.occupancy.rebuild(this.units); this.initiative.restore(snapshot.initiative); this.turns.restore(snapshot.phase, snapshot.hasMoved, snapshot.hasActed); this.random.state = snapshot.randomState; this.activeUnit = snapshot.activeUnitId ? this.units.find((unit) => unit.id === snapshot.activeUnitId) : undefined; this.objectives.states.splice(0, this.objectives.states.length, ...snapshot.objectives.map((objective) => ({ ...objective }))); this.log.splice(0, this.log.length, ...snapshot.log.slice(-50)); }
  cloneUnits(): UnitBattleState[] { return this.units.map(cloneUnit); }
  private requireActive(): UnitBattleState { if (!this.activeUnit?.alive) throw new Error('No living active unit.'); return this.activeUnit; }
  private requireUnit(id: UnitId): UnitBattleState { const unit = this.units.find((item) => item.id === id); if (!unit) throw new Error(`Missing target ${id}.`); return unit; }
  private addLog(message: string): void { this.log.push(message); if (this.log.length > 50) this.log.shift(); }
  private terminal(): boolean { return this.turns.phase === 'battleWon' || this.turns.phase === 'battleLost'; }
}
export class BattleComplete extends Error { constructor(readonly result: 'won' | 'lost') { super(`Battle ${result}.`); } }
