import type { ResolvedTile } from '../data/tactical/TacticalSchemas'; import type { UnitBattleState, WeaponProfile } from './CombatTypes'; import { facingRelation, type FacingRelation } from './Facing';
export const COMBAT_RULES = Object.freeze({ baseHit: 70, sideHit: 10, rearHit: 20, rearDamage: 1.2, uphillHitPerLevel: -5, downhillHitPerLevel: 3, criticalMultiplier: 1.5, minimumDamage: 1 });
export interface AttackPreview { readonly valid: boolean; readonly reason?: string; readonly hitChance: number; readonly criticalChance: number; readonly damage: number; readonly expectedDamage: number; readonly relation: FacingRelation; readonly elevationModifier: number; readonly counterRisk: boolean; readonly hpBefore: number; readonly projectedHp: number; }
export function distance(a: UnitBattleState['position'], b: UnitBattleState['position']): number { return Math.abs(a.x - b.x) + Math.abs(a.y - b.y); }
export function targetValid(actor: UnitBattleState, target: UnitBattleState, weapon: WeaponProfile, actorTile: ResolvedTile, targetTile: ResolvedTile, hasLineOfSight: boolean): string | undefined { if (!actor.alive) return 'Actor is defeated.'; if (!target.alive) return 'Target is defeated.'; if (actor.team === target.team) return 'Cannot target an ally.'; const range = distance(actor.position, target.position); if (range < weapon.minRange || range > weapon.maxRange) return 'Target is outside weapon range.'; if (Math.abs(actorTile.elevation - targetTile.elevation) > weapon.maxElevationDelta) return 'Elevation difference is too great.'; if (!hasLineOfSight) return 'Line of sight is blocked.'; return undefined; }
export function hitChance(actor: UnitBattleState, target: UnitBattleState, weapon: WeaponProfile, actorTile: ResolvedTile, targetTile: ResolvedTile): number { const relation = facingRelation(actor.position, target.position, target.facing); const facing = relation === 'rear' ? COMBAT_RULES.rearHit : relation === 'side' ? COMBAT_RULES.sideHit : 0; const elevation = actorTile.elevation > targetTile.elevation ? (actorTile.elevation - targetTile.elevation) * 3 : (targetTile.elevation - actorTile.elevation) * -5; return clamp(COMBAT_RULES.baseHit + actor.accuracy - target.evasion + weapon.accuracyModifier + facing + elevation, 5, 100); }
export function damage(actor: UnitBattleState, target: UnitBattleState, weapon: WeaponProfile, guardMultiplier = 1): number { const relation = facingRelation(actor.position, target.position, target.facing); const raw = actor.physicalAttack + weapon.power - target.physicalDefense * .7; return Math.max(COMBAT_RULES.minimumDamage, Math.floor(raw * (relation === 'rear' ? COMBAT_RULES.rearDamage : 1) * guardMultiplier)); }
export function criticalChance(actor: UnitBattleState, weapon: WeaponProfile): number { return clamp(actor.criticalChance + weapon.criticalModifier, 0, 50); }
export function previewAttack(actor: UnitBattleState, target: UnitBattleState, weapon: WeaponProfile, actorTile: ResolvedTile, targetTile: ResolvedTile, hasLineOfSight: boolean, guardMultiplier: number, counterRisk: boolean): AttackPreview { const reason = targetValid(actor, target, weapon, actorTile, targetTile, hasLineOfSight); const hit = reason ? 0 : hitChance(actor, target, weapon, actorTile, targetTile); const baseDamage = reason ? 0 : damage(actor, target, weapon, guardMultiplier); const critical = reason ? 0 : criticalChance(actor, weapon); const expected = baseDamage * (hit / 100) * (1 + critical / 100 * (COMBAT_RULES.criticalMultiplier - 1)); return { valid: !reason, reason, hitChance: hit, criticalChance: critical, damage: baseDamage, expectedDamage: expected, relation: facingRelation(actor.position, target.position, target.facing), elevationModifier: actorTile.elevation - targetTile.elevation, counterRisk, hpBefore: target.currentHp, projectedHp: Math.max(0, target.currentHp - Math.round(expected)) }; }
function clamp(value: number, min: number, max: number): number { return Math.min(max, Math.max(min, value)); }
