import type { AiProfile, BattleDefinition, CombatData, StatusDefinition, UnitPlacement, UnitTemplate, WeaponProfile } from './CombatTypes';
import { templateId, unitId, weaponId } from './CombatTypes';

export type DataResult<T> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly issues: readonly string[] };
const facings = new Set(['north', 'east', 'south', 'west']); const teams = new Set(['allies', 'enemies']); const aiIds = new Set(['aggressiveMelee', 'cautiousRanged', 'defensive']); const statusIds = new Set(['guard', 'haste', 'slow', 'poison']);
export function validateCombatData(input: unknown): DataResult<CombatData> {
  const issues: string[] = []; if (!record(input) || input.version !== 1) return { ok: false, issues: ['Combat data must be a version 1 object.'] };
  const templates = array(input.templates).filter((v): v is UnitTemplate => validTemplate(v, issues)); const weapons = array(input.weapons).filter((v): v is WeaponProfile => validWeapon(v, issues)); const aiProfiles = array(input.aiProfiles).filter((v): v is AiProfile => validAi(v, issues)); const statuses = array(input.statuses).filter((v): v is StatusDefinition => validStatus(v, issues));
  const abilities = array(input.abilities).filter((v): v is CombatData['abilities'][number] => record(v) && text(v.id) && text(v.name) && nonNegative(v.mpCost) && positive(v.range) && typeof v.permitsCounter === 'boolean');
  unique(templates.map((v) => v.id), 'template', issues); unique(weapons.map((v) => v.id), 'weapon', issues); unique(aiProfiles.map((v) => v.id), 'AI profile', issues);
  const weaponIds = new Set(weapons.map((v) => v.id)); const profiles = new Set(aiProfiles.map((v) => v.id)); for (const template of templates) { if (!weaponIds.has(template.weaponId)) issues.push(`Template ${template.id} references a missing weapon.`); if (!profiles.has(template.aiProfile)) issues.push(`Template ${template.id} references a missing AI profile.`); }
  return issues.length ? { ok: false, issues } : { ok: true, value: { version: 1, templates, weapons, abilities, aiProfiles, statuses } };
}
export function validateBattleDefinition(input: unknown, data: CombatData): DataResult<BattleDefinition> {
  const issues: string[] = []; if (!record(input) || input.version !== 1 || !text(input.id) || !text(input.mapId) || !Number.isInteger(input.seed)) return { ok: false, issues: ['Battle definition header is invalid.'] };
  const units = array(input.units).filter((v): v is UnitPlacement => validPlacement(v, issues)); unique(units.map((v) => v.id), 'unit', issues); unique(units.map((v) => `${v.position.x},${v.position.y}`), 'spawn position', issues);
  const templates = new Set(data.templates.map((v) => v.id)); for (const unit of units) if (!templates.has(unit.templateId)) issues.push(`Unit ${unit.id} references a missing template.`);
  const objectives = array(input.objectives).filter((v): v is BattleDefinition['objectives'][number] => record(v) && text(v.id) && ['defeatAllEnemies', 'keepAllyAlive'].includes(v.type as string) && text(v.description));
  if (!objectives.length) issues.push('Battle requires at least one objective.');
  return issues.length ? { ok: false, issues } : { ok: true, value: { version: 1, id: input.id, mapId: input.mapId, units, objectives, seed: input.seed as number } };
}
function validTemplate(value: unknown, issues: string[]): value is UnitTemplate { if (!record(value) || !text(value.id) || !text(value.displayName) || !text(value.jobId) || !positive(value.level) || !record(value.stats) || !text(value.weaponId) || !Array.isArray(value.abilities) || !value.abilities.every(text) || !aiIds.has(value.aiProfile as string)) { issues.push('Invalid unit template.'); return false; } const s = value.stats; const validStats = ['maxHp','maxMp','speed','move','jump','physicalAttack','physicalDefense','magicAttack','magicDefense','accuracy','evasion','criticalChance'].every((key) => nonNegative(s[key])); if (!validStats || !positive(s.maxHp) || !positive(s.speed)) { issues.push(`Invalid stats for template ${value.id}.`); return false; } value.id = templateId(value.id); value.weaponId = weaponId(value.weaponId); return true; }
function validWeapon(value: unknown, issues: string[]): value is WeaponProfile { const valid = record(value) && text(value.id) && text(value.name) && ['sword','bow'].includes(value.category as string) && positive(value.power) && nonNegative(value.minRange) && positive(value.maxRange) && positive(value.maxElevationDelta) && finite(value.accuracyModifier) && finite(value.criticalModifier) && typeof value.permitsCounter === 'boolean'; if (!valid) issues.push('Invalid weapon profile.'); else value.id = weaponId(value.id as string); return valid; }
function validAi(value: unknown, issues: string[]): value is AiProfile { const valid = record(value) && aiIds.has(value.id as string) && ['killWeight','damageWeight','hitWeight','rearWeight','sideWeight','hazardPenalty','maxDestinations','maxTargets','maxOperations'].every((key) => nonNegative(value[key])); if (!valid) issues.push('Invalid AI profile.'); return valid; }
function validStatus(value: unknown, issues: string[]): value is StatusDefinition { const valid = record(value) && statusIds.has(value.id as string) && ['refresh','stack','ignore'].includes(value.stackPolicy as string) && positive(value.speedMultiplier) && positive(value.damageMultiplier) && nonNegative(value.poisonDamage); if (!valid) issues.push('Invalid status definition.'); return valid; }
function validPlacement(value: unknown, issues: string[]): value is UnitPlacement { const valid = record(value) && text(value.id) && text(value.templateId) && teams.has(value.team as string) && record(value.position) && Number.isInteger(value.position.x) && Number.isInteger(value.position.y) && facings.has(value.facing as string) && typeof value.controllable === 'boolean' && Number.isInteger(value.spawnOrder); if (!valid) issues.push('Invalid unit placement.'); else { value.id = unitId(value.id as string); value.templateId = templateId(value.templateId as string); } return valid; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); } function array(value: unknown): unknown[] { return Array.isArray(value) ? value : []; } function text(value: unknown): value is string { return typeof value === 'string' && value.length > 0; } function finite(value: unknown): value is number { return typeof value === 'number' && Number.isFinite(value); } function nonNegative(value: unknown): value is number { return finite(value) && value >= 0; } function positive(value: unknown): value is number { return finite(value) && value > 0; } function unique(values: readonly unknown[], label: string, issues: string[]): void { if (new Set(values).size !== values.length) issues.push(`Duplicate ${label}.`); }
