import type { UnitBattleState, UnitId } from './CombatTypes'; import type { StatusSystem } from './StatusSystem';
export const CT_READY = 100; export interface InitiativeState { readonly activeUnitId?: UnitId; readonly paused: boolean; }
export class Initiative { private active: UnitId | undefined; private paused = false; constructor(private readonly units: UnitBattleState[], private readonly statuses: StatusSystem, readonly threshold = CT_READY) {}
  get activeUnitId(): UnitId | undefined { return this.active; }
  advance(maxSteps = 10_000): UnitBattleState { if (this.active) throw new Error('Cannot advance while a turn is active.'); let steps = 0; while (steps < maxSteps) { steps += 1; for (const unit of this.units) if (unit.alive) unit.chargeTime += unit.speed * this.statuses.initiativeMultiplier(unit); const ready = this.readyUnits(); if (ready.length) { const unit = ready[0] as UnitBattleState; this.active = unit.id; this.paused = true; return unit; } } throw new Error('Initiative could not produce a ready unit.'); }
  completeTurn(unitId: UnitId): void { if (this.active !== unitId) throw new Error('Only the active unit may complete a turn.'); const unit = this.units.find((item) => item.id === unitId); if (unit) unit.chargeTime = Math.max(0, unit.chargeTime - this.threshold); this.active = undefined; this.paused = false; }
  preview(count = 5): readonly UnitId[] { const clones = this.units.filter((u) => u.alive).map((u) => ({ id: u.id, speed: u.speed * this.statuses.initiativeMultiplier(u), ct: u.chargeTime, spawnOrder: u.spawnOrder })); const result: UnitId[] = []; let guard = 0; while (result.length < count && clones.length && guard++ < count * 10_000) { for (const unit of clones) unit.ct += unit.speed; const ready = clones.filter((u) => u.ct >= this.threshold).sort(compareInitiative); if (ready[0]) { ready[0].ct -= this.threshold; result.push(ready[0].id); } } return result; }
  removeDefeated(): void { if (this.active && !this.units.find((u) => u.id === this.active)?.alive) { this.active = undefined; this.paused = false; } }
  restart(): void { for (const unit of this.units) unit.chargeTime = 0; this.active = undefined; this.paused = false; }
  serialize(): InitiativeState { return { activeUnitId: this.active, paused: this.paused }; }
  restore(state: InitiativeState): void { if (state.activeUnitId && !this.units.some((u) => u.id === state.activeUnitId && u.alive)) throw new Error('Invalid active initiative unit.'); this.active = state.activeUnitId; this.paused = state.paused; }
  private readyUnits(): UnitBattleState[] { return this.units.filter((u) => u.alive && u.chargeTime >= this.threshold).sort((a, b) => (b.chargeTime - this.threshold) - (a.chargeTime - this.threshold) || b.speed - a.speed || a.spawnOrder - b.spawnOrder || a.id.localeCompare(b.id)); }
}
function compareInitiative(a: { ct: number; speed: number; spawnOrder: number; id: UnitId }, b: { ct: number; speed: number; spawnOrder: number; id: UnitId }): number { return (b.ct - CT_READY) - (a.ct - CT_READY) || b.speed - a.speed || a.spawnOrder - b.spawnOrder || a.id.localeCompare(b.id); }
