import type { Facing, StatusState, UnitBattleState, UnitPlacement, UnitTemplate } from './CombatTypes';
export function createUnit(template: UnitTemplate, placement: UnitPlacement): UnitBattleState { const stats = template.stats; return { id: placement.id, templateId: template.id, displayName: template.displayName, team: placement.team, jobId: template.jobId, level: template.level, position: { ...placement.position }, facing: placement.facing, currentHp: stats.maxHp, maxHp: stats.maxHp, currentMp: stats.maxMp, maxMp: stats.maxMp, speed: stats.speed, chargeTime: 0, move: stats.move, jump: stats.jump, physicalAttack: stats.physicalAttack, physicalDefense: stats.physicalDefense, magicAttack: stats.magicAttack, magicDefense: stats.magicDefense, accuracy: stats.accuracy, evasion: stats.evasion, criticalChance: stats.criticalChance, weaponId: template.weaponId, abilities: [...template.abilities], statuses: [], alive: true, controllable: placement.controllable, aiProfile: template.aiProfile, spawnOrder: placement.spawnOrder }; }
export function cloneUnit(unit: UnitBattleState): UnitBattleState { return { ...unit, position: { ...unit.position }, abilities: [...unit.abilities], statuses: unit.statuses.map((status) => ({ ...status })) }; }
export function applyDamage(unit: UnitBattleState, amount: number): number { requireFinite(amount); const damage = Math.max(0, Math.floor(amount)); unit.currentHp = Math.max(0, unit.currentHp - damage); if (unit.currentHp === 0) unit.alive = false; return damage; }
export function heal(unit: UnitBattleState, amount: number): number { requireFinite(amount); if (!unit.alive) return 0; const before = unit.currentHp; unit.currentHp = Math.min(unit.maxHp, unit.currentHp + Math.max(0, Math.floor(amount))); return unit.currentHp - before; }
export function moveUnit(unit: UnitBattleState, x: number, y: number): void { if (!unit.alive || !Number.isInteger(x) || !Number.isInteger(y)) throw new Error('Invalid unit movement.'); unit.position = { x, y }; }
export function changeFacing(unit: UnitBattleState, facing: Facing): void { unit.facing = facing; }
export function addStatus(unit: UnitBattleState, status: StatusState, policy: 'refresh' | 'stack' | 'ignore'): void { if (!unit.alive || status.duration <= 0) return; const current = unit.statuses.find((item) => item.id === status.id); if (!current) { unit.statuses.push({ ...status }); return; } if (policy === 'refresh') current.duration = Math.max(current.duration, status.duration); else if (policy === 'stack') { current.duration = Math.max(current.duration, status.duration); current.stacks += status.stacks; } }
export function removeStatus(unit: UnitBattleState, id: StatusState['id']): void { unit.statuses = unit.statuses.filter((status) => status.id !== id); }
export function markDefeated(unit: UnitBattleState): void { unit.currentHp = 0; unit.alive = false; }
export function canAct(unit: UnitBattleState): boolean { return unit.alive && unit.currentHp > 0; }
export function isTargetable(unit: UnitBattleState): boolean { return unit.alive && unit.currentHp > 0; }
function requireFinite(value: number): void { if (!Number.isFinite(value)) throw new Error('Numeric mutation must be finite.'); }
