import type { AudioManager } from '../audio/AudioManager';
import { BattleComplete, BattleController } from '../combat/BattleController';
import { CombatDataLoader } from '../combat/CombatDataLoader';
import type { BattleDefinition, CombatData, Facing, UnitBattleState, UnitId } from '../combat/CombatTypes';
import type { AttackPreview } from '../combat/CombatFormula';
import type { Scene } from '../core/Scene';
import type { TimeSnapshot } from '../core/Time';
import { MapLoader } from '../data/tactical/MapLoader';
import type { TacticalMap } from '../data/tactical/TacticalMap';
import type { InputManager } from '../input/InputManager';
import type { Camera, Point } from '../rendering/Camera';
import type { CanvasRenderer } from '../rendering/CanvasRenderer';
import { TacticalRenderPipeline } from '../rendering/tactical/TacticalRenderPipeline';
import { TileHighlights } from '../rendering/TileHighlights';
import type { AppShell } from '../ui/AppShell';
import type { GridPoint } from '../world/GridCoordinates';
import { IsometricGrid } from '../world/IsometricGrid';

type CommandMode = 'move' | 'attack' | 'inspect';
interface MovementAnimation { readonly unitId: UnitId; readonly path: readonly GridPoint[]; index: number; elapsed: number; }
export interface TacticalSceneDebug { readonly tile?: Point; readonly elevation?: number; readonly terrain?: string; readonly selected?: Point; readonly pathNodes: number; readonly drawCalls: number; readonly battlePhase?: string; readonly activeUnit?: string; readonly initiative?: string; readonly command?: string; readonly aiCandidates?: number; readonly aiScore?: number; readonly randomState?: number; readonly occupancy?: string; readonly lineOfSight?: string; }

export class EngineDemoScene implements Scene {
  readonly id = 'demo'; private readonly mapLoader = new MapLoader(); private readonly combatLoader = new CombatDataLoader(); private readonly highlights = new TileHighlights(); private readonly pipeline = new TacticalRenderPipeline(); private readonly abort = new AbortController();
  private map: TacticalMap | undefined; private grid: IsometricGrid | undefined; private combatData: CombatData | undefined; private battleDefinition: BattleDefinition | undefined; private battle: BattleController | undefined; private hovered: GridPoint | undefined; private cursor: GridPoint = { x: 0, y: 0 }; private mode: CommandMode | undefined; private path: readonly GridPoint[] = []; private targetable = new Set<UnitId>(); private selectedUnitId: UnitId | undefined; private preview: AttackPreview | undefined; private movement: MovementAnimation | undefined; private readonly presentationPositions = new Map<UnitId, Point>(); private impactUnitId: UnitId | undefined; private impactTime = 0; private enemyDelay = 0;
  constructor(private readonly renderer: CanvasRenderer, readonly camera: Camera, private readonly input: InputManager, private readonly panSpeed: number, private readonly shell: AppShell, private readonly audio: AudioManager, private readonly isDebugEnabled: () => boolean) {}
  async enter(): Promise<void> { const base = import.meta.env.BASE_URL; const [mapResult, combatResult] = await Promise.all([this.mapLoader.loadUrl(`${base}maps/combat-prototype.json`, this.abort.signal), this.combatLoader.load(`${base}data/combat-prototype.json`, `${base}data/battle-prototype.json`, this.abort.signal)]); if (!mapResult.ok) throw new Error(`Map unavailable: ${mapResult.message}`); if (!combatResult.ok) throw new Error(`Combat data unavailable: ${combatResult.issues.join(' ')}`); this.map = mapResult.map; this.grid = new IsometricGrid(mapResult.map.data); this.combatData = combatResult.value.data; this.battleDefinition = combatResult.value.battle; this.initializeBattle(); this.fitMap(); this.shell.setBattleCallbacks({ move: () => this.selectCommand('move'), attack: () => this.selectCommand('attack'), wait: () => this.wait(), endTurn: () => this.endTurn(), cancel: () => this.cancel(), inspect: () => this.selectCommand('inspect'), restart: () => this.initializeBattle(), facing: (value) => this.setFacing(value) }); }
  update(time: TimeSnapshot): void { const map = this.map; const grid = this.grid; if (!map || !grid || !this.battle) return; if (this.impactTime > 0) { this.impactTime -= time.deltaSeconds; if (this.impactTime <= 0) this.impactUnitId = undefined; } if (this.movement) { this.updateMovement(time.deltaSeconds); this.camera.update(time.deltaSeconds, reducedMotion()); return; } this.updateCamera(time); this.updateCursor(); this.hovered = grid.screenToGrid(this.input.pointer, this.viewportPoint(), this.camera, map); if (this.input.pointerPressed && this.hovered) this.confirmTile(this.hovered); if (this.input.state('confirm').pressed) this.confirmTile(this.cursor); if (this.input.state('cancel').pressed) this.cancel(); if (this.input.state('commandMove').pressed) this.selectCommand('move'); if (this.input.state('commandAttack').pressed) this.selectCommand('attack'); if (this.input.state('inspect').pressed) this.selectCommand('inspect'); if (this.input.state('endTurn').pressed) this.endTurn(); if (this.input.state('focus').pressed) this.focusActive(); if (this.battle.activeUnit && !this.battle.activeUnit.controllable && this.battle.turns.phase === 'enemyThinking') { this.enemyDelay += time.deltaSeconds; if (this.enemyDelay >= (reducedMotion() ? 0 : .25)) { this.enemyDelay = 0; this.runEnemy(); } } this.refreshHoverPreview(); }
  render(): void { const battle = this.battle; if (!this.map || !this.grid || !battle) { this.renderer.begin('#0b1017'); return; } this.pipeline.render({ renderer: this.renderer, camera: this.camera, map: this.map, grid: this.grid, highlights: this.highlights, selected: this.cursor, hovered: this.hovered, debug: this.isDebugEnabled(), path: this.path, units: battle.units, activeUnitId: battle.activeUnit?.id, selectedUnitId: this.selectedUnitId, hoveredUnitId: this.unitAt(this.hovered)?.id, impactUnitId: this.impactUnitId, targetableUnitIds: this.targetable, presentationPositions: this.presentationPositions }); }
  exit(): void { this.shell.setBattleCallbacks(); this.shell.updateTacticalStatus(); this.camera.follow(); }
  dispose(): void { this.abort.abort(); this.highlights.clear(); this.battle?.events.clear(); }
  get debugSnapshot(): TacticalSceneDebug { const tile = this.hovered && this.map?.get(this.hovered.x, this.hovered.y); const battle = this.battle; return { tile: this.hovered, elevation: tile?.elevation, terrain: tile?.terrain.name, selected: this.cursor, pathNodes: this.path.length, drawCalls: this.pipeline.drawCalls, battlePhase: battle?.turns.phase, activeUnit: battle?.activeUnit?.id, initiative: battle?.units.map((u) => `${u.id}:${Math.floor(u.chargeTime)}`).join(' '), command: this.mode, aiCandidates: battle?.lastAiDecision?.candidates, aiScore: battle?.lastAiDecision?.score, randomState: battle?.random.state, occupancy: battle ? JSON.stringify(battle.occupancy.snapshot()) : undefined, lineOfSight: battle?.resolver.lastLineOfSight?.cells.map((cell) => `${cell.x},${cell.y}`).join(' ') } as TacticalSceneDebug; }
  setFacing(facing: Facing): void { try { this.battle?.setFacing(facing); this.audio.playEffect('select'); this.refreshHud(); } catch (error) { this.report(error); } }
  private initializeBattle(): void { const map = this.map; const data = this.combatData; const definition = this.battleDefinition; if (!map || !data || !definition) return; this.battle?.events.clear(); this.battle = new BattleController(map, data, definition); this.mode = undefined; this.path = []; this.preview = undefined; this.targetable.clear(); this.presentationPositions.clear(); try { const active = this.battle.start(); this.cursor = { ...active.position }; this.selectedUnitId = active.id; this.audio.playEffect('ready'); this.shell.announce(`${active.displayName} is ready.`); this.focusActive(); } catch (error) { if (!(error instanceof BattleComplete)) this.report(error); } this.refreshHighlights(); this.refreshHud(); }
  private selectCommand(mode: CommandMode): void { const battle = this.battle; if (!battle?.activeUnit?.controllable || battle.turns.phase !== 'awaitingCommand') return; if (mode === 'move' && battle.turns.hasMoved || mode === 'attack' && battle.turns.hasActed) { this.shell.announce(`${mode} has already been used.`); return; } this.mode = mode; this.path = []; this.preview = undefined; this.targetable.clear(); this.audio.playEffect('select'); this.shell.announce(`${mode} command selected.`); this.refreshHighlights(); this.refreshHud(); }
  private confirmTile(point: GridPoint): void { const battle = this.battle; if (!battle?.activeUnit?.controllable || battle.turns.phase !== 'awaitingCommand') return; this.cursor = point; if (this.mode === 'move') this.executeMove(point); else if (this.mode === 'attack') { const target = this.unitAt(point); if (target) this.executeAttack(target.id); } else { const unit = this.unitAt(point); this.selectedUnitId = unit?.id; if (unit) this.shell.announce(`${unit.displayName}, ${unit.currentHp} of ${unit.maxHp} HP.`); } this.refreshHighlights(); this.refreshHud(); }
  private executeMove(destination: GridPoint): void { const battle = this.battle; const grid = this.grid; if (!battle || !grid) return; try { const actorId = battle.activeUnit?.id; const path = battle.moveActive(destination); if (actorId && path.length) { this.path = path; this.startMovement(actorId, path); } this.mode = undefined; this.audio.playEffect('move'); this.shell.announce(`Movement committed to ${destination.x}, ${destination.y}.`); } catch (error) { this.report(error); } }
  private executeAttack(targetId: UnitId): void { const battle = this.battle; if (!battle) return; try { this.audio.playEffect('attack'); const result = battle.attack(targetId); this.mode = undefined; this.preview = undefined; this.targetable.clear(); this.impactUnitId = targetId; this.impactTime = .22; this.audio.playEffect(result.hit ? 'hit' : 'miss'); this.shell.announce(result.events.join(' ')); if (result.defeated) this.audio.playEffect('defeat'); if (battle.turns.phase === 'battleWon' || battle.turns.phase === 'battleLost') this.terminal(battle.turns.phase === 'battleWon'); } catch (error) { this.report(error); } this.refreshHighlights(); this.refreshHud(); }
  private wait(): void { const battle = this.battle; if (!battle?.activeUnit?.controllable) return; battle.statuses.apply(battle.activeUnit, 'guard', 2, battle.activeUnit.id); this.shell.announce(`${battle.activeUnit.displayName} guards and waits.`); this.endTurn(); }
  private endTurn(): void { const battle = this.battle; if (!battle?.activeUnit?.controllable || battle.turns.phase !== 'awaitingCommand') return; try { const next = battle.endTurn(); this.mode = undefined; this.path = []; this.targetable.clear(); if (next) { this.cursor = { ...next.position }; this.selectedUnitId = next.id; this.shell.announce(`${next.displayName} is ready.`); this.audio.playEffect('ready'); this.focusActive(); } } catch (error) { this.report(error); } this.refreshHighlights(); this.refreshHud(); }
  private runEnemy(): void { const battle = this.battle; if (!battle) return; try { const result = battle.runEnemyTurn(); if (result.path.length) this.startMovement(result.actorId, result.path); if (result.action) { this.audio.playEffect('attack'); this.impactUnitId = result.action.targetId; this.impactTime = .22; this.audio.playEffect(result.action.hit ? 'hit' : 'miss'); this.shell.announce(result.action.events.join(' ')); } const active = battle.activeUnit; if (active) { this.cursor = { ...active.position }; this.selectedUnitId = active.id; if (active.controllable) { this.audio.playEffect('ready'); this.shell.announce(`${active.displayName} is ready.`); this.focusActive(); } } else if (battle.turns.phase === 'battleWon' || battle.turns.phase === 'battleLost') this.terminal(battle.turns.phase === 'battleWon'); } catch (error) { this.report(error); } this.refreshHighlights(); this.refreshHud(); }
  private cancel(): void { if (!this.mode) return; this.mode = undefined; this.preview = undefined; this.path = []; this.targetable.clear(); this.audio.playEffect('select'); this.shell.announce('Command canceled.'); this.refreshHighlights(); this.refreshHud(); }
  private refreshHighlights(): void { const battle = this.battle; if (!battle) return; this.highlights.clear(); this.highlights.set('cursor', [{ point: this.cursor, kind: 'selection' }]); if (this.mode === 'move') this.highlights.set('movement', [...battle.reachable().values()].map((entry) => ({ point: entry.point, kind: 'movement' as const, label: entry.remaining.toFixed(1) }))); if (this.mode === 'attack') { this.targetable = new Set(battle.units.filter((unit) => unit.team !== battle.activeUnit?.team && battle.resolver.preview(battle.activeUnit as UnitBattleState, unit).valid).map((unit) => unit.id)); this.highlights.set('attack', battle.units.filter((unit) => this.targetable.has(unit.id)).map((unit) => ({ point: unit.position, kind: 'attack' as const }))); } }
  private refreshHoverPreview(): void { const battle = this.battle; const target = this.unitAt(this.hovered); if (this.mode === 'attack' && battle?.activeUnit && target && this.targetable.has(target.id)) { const next = battle.previewAttack(target.id); this.highlights.set('los', (battle.resolver.lastLineOfSight?.cells ?? []).map((point) => ({ point, kind: 'ability' as const }))); if (JSON.stringify(next) !== JSON.stringify(this.preview)) { this.preview = next; this.path = []; this.refreshHud(); } } }
  private refreshHud(): void { const battle = this.battle; const active = battle?.activeUnit; if (!battle || !active) return; const weapon = battle.data.weapons.find((item) => item.id === active.weaponId); const preview = this.preview; this.shell.renderBattleHud({ active: `${active.displayName} · ${active.team}`, stats: `HP ${active.currentHp}/${active.maxHp} · MP ${active.currentMp}/${active.maxMp} · CT ${Math.floor(active.chargeTime)} · SPD ${active.speed}`, weapon: weapon?.name ?? active.weaponId, statuses: active.statuses.length ? active.statuses.map((status) => `${status.id} ${status.duration}`).join(', ') : 'No statuses', timeline: battle.initiative.preview(5).map((id) => battle.units.find((unit) => unit.id === id)?.displayName ?? id).join(' › '), objective: battle.objectives.states.map((objective) => `${objective.description} [${objective.status}]`).join(' '), preview: preview ? `${preview.valid ? '' : `Blocked: ${preview.reason} · `}Hit ${preview.hitChance}% · Damage ${preview.damage} (~${preview.expectedDamage.toFixed(1)}) · Crit ${preview.criticalChance}% · ${preview.relation} · Elevation ${preview.elevationModifier >= 0 ? '+' : ''}${preview.elevationModifier} · Counter ${preview.counterRisk ? 'possible' : 'none'} · HP ${preview.hpBefore} → est. ${preview.projectedHp}` : undefined, log: battle.log, terminal: battle.turns.phase === 'battleWon' ? 'Victory' : battle.turns.phase === 'battleLost' ? 'Defeat' : undefined }); }
  private updateCamera(time: TimeSnapshot): void { let dx = 0; let dy = 0; if (this.input.state('panLeft').down) dx -= 1; if (this.input.state('panRight').down) dx += 1; if (this.input.state('panUp').down) dy -= 1; if (this.input.state('panDown').down) dy += 1; if (dx || dy) { this.camera.follow(); this.camera.panInertial(dx * this.panSpeed / this.camera.zoom, dy * this.panSpeed / this.camera.zoom); } if (this.input.dragDelta.x || this.input.dragDelta.y) { this.camera.follow(); this.camera.pan(-this.input.dragDelta.x / this.camera.zoom, -this.input.dragDelta.y / this.camera.zoom); } if (this.input.wheelDelta) this.camera.setZoomSmooth(this.camera.zoom * Math.exp(-this.input.wheelDelta * .0015)); if (this.input.pointerActive && this.input.pointerType === 'mouse' && !this.input.pointerDown) this.camera.edgeScroll(this.input.pointer, this.viewportPoint(), time.deltaSeconds); this.camera.update(time.deltaSeconds, reducedMotion()); }
  private updateCursor(): void { const map = this.map; if (!map) return; let x = this.cursor.x; let y = this.cursor.y; if (this.input.state('cursorLeft').pressed) x -= 1; if (this.input.state('cursorRight').pressed) x += 1; if (this.input.state('cursorUp').pressed) y -= 1; if (this.input.state('cursorDown').pressed) y += 1; if (map.inBounds(x, y)) { this.cursor = { x, y }; this.hovered = this.cursor; } }
  private startMovement(unitId: UnitId, path: readonly GridPoint[]): void { if (path.length < 2 || !this.grid || reducedMotion()) return; this.movement = { unitId, path, index: 0, elapsed: 0 }; const first = path[0]; if (first) this.presentationPositions.set(unitId, this.grid.gridToWorld({ ...first, elevation: this.map?.require(first.x, first.y).elevation ?? 0 })); this.camera.follow(() => this.presentationPositions.get(unitId) ?? { x: this.camera.x, y: this.camera.y }); }
  private updateMovement(delta: number): void { const movement = this.movement; const grid = this.grid; const map = this.map; if (!movement || !grid || !map) return; movement.elapsed += delta; const duration = .12; while (movement.elapsed >= duration) { movement.elapsed -= duration; movement.index += 1; if (movement.index >= movement.path.length - 1) { this.presentationPositions.delete(movement.unitId); this.movement = undefined; this.camera.follow(); return; } } const from = movement.path[movement.index]; const to = movement.path[movement.index + 1]; if (!from || !to) return; const a = grid.gridToWorld({ ...from, elevation: map.require(from.x, from.y).elevation }); const b = grid.gridToWorld({ ...to, elevation: map.require(to.x, to.y).elevation }); const t = movement.elapsed / duration; this.presentationPositions.set(movement.unitId, { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t }); }
  private unitAt(point?: GridPoint): UnitBattleState | undefined { if (!point || !this.battle) return undefined; const id = this.battle.occupancy.unitAt(point); return id ? this.battle.units.find((unit) => unit.id === id) : undefined; }
  private terminal(won: boolean): void { this.mode = undefined; this.targetable.clear(); this.audio.playEffect(won ? 'victory' : 'loss'); this.shell.announce(won ? 'Battle won.' : 'Battle lost.'); }
  private focusActive(): void { const unit = this.battle?.activeUnit; const grid = this.grid; const map = this.map; if (!unit || !grid || !map) return; const world = grid.gridToWorld({ ...unit.position, elevation: map.require(unit.position.x, unit.position.y).elevation }); this.camera.focusSmooth(world.x, world.y, this.camera.zoom); }
  private fitMap(): void { const map = this.map; const grid = this.grid; if (!map || !grid) return; const corners = [{ x: 0, y: 0 }, { x: map.data.width - 1, y: 0 }, { x: 0, y: map.data.height - 1 }, { x: map.data.width - 1, y: map.data.height - 1 }].map((point) => grid.gridToWorld({ ...point, elevation: map.require(point.x, point.y).elevation })); this.camera.fitBounds({ x: Math.min(...corners.map((p) => p.x)) - grid.halfWidth, y: Math.min(...corners.map((p) => p.y)) - map.data.elevationStep - grid.halfHeight }, { x: Math.max(...corners.map((p) => p.x)) + grid.halfWidth, y: Math.max(...corners.map((p) => p.y)) + grid.halfHeight }, this.viewportPoint(), 72); }
  private viewportPoint(): Point { return { x: this.renderer.viewport.size.width, y: this.renderer.viewport.size.height }; }
  private report(error: unknown): void { const message = error instanceof Error ? error.message : 'Battle command failed.'; this.shell.announce(message); console.warn(message); }
}
function reducedMotion(): boolean { return matchMedia('(prefers-reduced-motion: reduce)').matches; }
